# Generated by Django 5.0.3 on 2024-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_balance', models.IntegerField()),
                ('sid', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('currency_name', models.CharField(max_length=255)),
                ('currency_id', models.CharField(max_length=255)),
            ],
        ),
    ]
