# Generated by Django 5.0.3 on 2024-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardhistory',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='current_balance',
            field=models.FloatField(),
        ),
    ]
